module.exports = {
  dist: {
    src: [
    'bower_components/foundation-sites/js/foundation.core.js',
    'bower_components/foundation-sites/js/foundation.util.animationFrame.js',
		'bower_components/foundation-sites/js/foundation.util.keyboard.js',
		'bower_components/foundation-sites/js/foundation.util.mediaQuery.js',
		'bower_components/foundation-sites/js/foundation.util.menuNester.js',
		'bower_components/foundation-sites/js/foundation.util.motion.js',
		'bower_components/foundation-sites/js/foundation.util.onImagesLoaded.js',
		'bower_components/foundation-sites/js/foundation.util.randomId.js',
		'bower_components/foundation-sites/js/foundation.util.sizeAndCollision.js',
		'bower_components/foundation-sites/js/foundation.util.swipe.js',
		'bower_components/foundation-sites/js/foundation.util.triggers.js',
		'bower_components/foundation-sites/js/foundation.utils.timer.js',
    'bower_components/foundation-sites/js/foundation.abide.js',
		'bower_components/foundation-sites/js/foundation.accordion.js',
		'bower_components/foundation-sites/js/foundation.drilldown.js',
		'bower_components/foundation-sites/js/foundation.dropdown.js',
		'bower_components/foundation-sites/js/foundation.dropdownMenu.js',
		'bower_components/foundation-sites/js/foundation.equalizer.js',
		'bower_components/foundation-sites/js/foundation.interchange.js',
		'bower_components/foundation-sites/js/foundation.joyride.js',
		'bower_components/foundation-sites/js/foundation.magellan.js',
		'bower_components/foundation-sites/js/foundation.offcanvas.js',
		'bower_components/foundation-sites/js/foundation.orbit.js',
		'bower_components/foundation-sites/js/foundation.responsiveMenu.js',
		'bower_components/foundation-sites/js/foundation.responsiveToggle.js',
		'bower_components/foundation-sites/js/foundation.reveal.js',
		'bower_components/foundation-sites/js/foundation.slider.js',
		'bower_components/foundation-sites/js/foundation.sticky.js',
		'bower_components/foundation-sites/js/foundation.tabs.js',
		'bower_components/foundation-sites/js/foundation.toggler.js',
		'bower_components/foundation-sites/js/foundation.tooltip.js',

		'bower_components/foundation-sites/js/motion-ui.js',
		//'bower_components/foundation-sites/js/util-map.json',
		'bower_components/flexibility/dist/flexibility.js',
		//'js/navigation.js',
		//'skip-link-focus-fix.js',
		'bower_components/fitvids/jquery.fitvids.js',
		//'js/jquery.fancybox.js',
		//'js/jquery.fancybox-media.js',
		//'js/responsiveslides.js',
		'js/app.js'
    ],
    dest: 'build/production.js'
  }
}
